const EnumPopupPage = Object.freeze({
    "eNone":0, 
    "eLogin":1, 
    "eRegister":2, 
    "eAgentCode":3, 
    "eRequestInput":4, 
    "eRequestOutput":5, 
    "eAnnouncement":6, 
    "eRequestCoupon":7, 
    "eComp":8,
    "eLetter":9,
    "eInputList":10,
    "eOutputList":11,
    "eModifyInfo":12,
    "eAlert1":13,
    "eAlert2":14,
    "eAlert3":15,
    "eAlert4":16,
});
exports.EPopupPage = EnumPopupPage;